type Mutation {
  memberCreate(member: NewMember!): Member!
}

type Query {
  memberById(id: ID!): Member
}

type Member {
  id: ID!
  tenant_id: ID!
  first_name: String!
  middle_name: String
  last_name: String
  created_at: String!
  created_by: String!
  updated_at: String
  updated_by: String
}

input NewMember {
  first_name: String!
  middle_name: String
  last_name: String!
}
